attributes:
  - Smiling
  - Mouth_Slightly_Open
  - Eyeglasses
  - Bangs
  - Wearing_Hat
  - Mustache
  - No_Beard
  - Black_Hair
  - Bushy_Eyebrows
  - Arched_Eyebrows
  - High_Cheekbones
  - Bags_Under_Eyes
  - Big_Lips
  - Big_Nose
  - Double_Chin
  - Oval_Face
  - Receding_Hairline
  - Blond_Hair
  - Brown_Hair
  - Gray_Hair
  - Bald
  - Straight_Hair
  - Wavy_Hair
  - Sideburns
